name: Integration Tests

on:
  pull_request:

  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"

jobs:
  Specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0
      - run: shards install
      - run: crystal spec --tag integration
